# ckan.yaml
apiVersion: container-canary.nvidia.com/v1
kind: Validator
name: ckan
description: ckan container validator
checks:
  - name: uwsgi
    description: Correct number (4) of uwsgi processes running
    probe:
      exec:
        command:
          - /bin/sh
          - -c
          - "[ `ps auxww | awk '{print $4 }' | grep uwsgi | wc -l` = 4 ]"
  - name: listening
    description: Is CKAN listening on port 5000
    probe:
      httpGet:
        path: /
        port: 5000
      initialDelaySeconds: 10