name: Test ckan-spatial images (PR)

on:
  pull_request:
    types:
        - closed
    branches:
        - master
        - 'ckan-*.*'
        - '!ckan-main'
        - '!dev/ckan-*.*.*'
        - '!feature/*'
        - '!fix/*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: mjanez/ckan-spatial
  CONTEXT: .
  BRANCH: ${{ github.head_ref }}
  DOCKERFILE: Dockerfile
  PYTHON_DOCKERFILE: Dockerfile.py3.*
  HADOLINT_VERSION: 2.12.0

jobs:
  build_and_push_base:
    name: runner/test-ckan-spatial-base-pr:${{ github.head_ref }}.*
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Determine Python Dockerfile
        id: determine_dockerfile
        run: |
          if [[ "${{ env.PYTHON_DOCKERFILE }}" == "Dockerfile.py3.*" ]]; then
            REAL_DOCKERFILE=$(find ./${{ env.BRANCH }}/base -name "Dockerfile.py3.*" | head -n 1)
            REAL_DOCKERFILE_NAME=$(basename $REAL_DOCKERFILE)
            echo "PYTHON_DOCKERFILE=${REAL_DOCKERFILE_NAME}" >> $GITHUB_ENV
          else
            echo "PYTHON_DOCKERFILE=${{ env.PYTHON_DOCKERFILE }}" >> $GITHUB_ENV
          fi

      - name: Linting Dockerfile and annotate code inline in the github PR viewer
        id: hadolint
        uses: jbergstroem/hadolint-gh-action@v1.12.2
        with:
          dockerfile: ${{ env.CONTEXT }}/${{ env.BRANCH }}/base/${{ env.DOCKERFILE }}
          version: ${{ env.HADOLINT_VERSION }}
          annotate: true
          error_level: -1

      - name: Linting Python Dockerfile and annotate code inline in the github PR viewer
        id: python_hadolint
        uses: jbergstroem/hadolint-gh-action@v1.12.2
        with:
          dockerfile: ${{ env.CONTEXT }}/${{ env.BRANCH }}/base/${{ env.PYTHON_DOCKERFILE }}
          version: ${{ env.HADOLINT_VERSION }}
          annotate: true
          error_level: -1

  build_and_push_dev:
    name: runner/test-ckan-spatial-dev-pr:${{ github.head_ref }}.*
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Determine Python Dockerfile
        id: determine_dockerfile
        run: |
          if [[ "${{ env.PYTHON_DOCKERFILE }}" == "Dockerfile.py3.*" ]]; then
            REAL_DOCKERFILE=$(find ./${{ env.BRANCH }}/base -name "Dockerfile.py3.*" | head -n 1)
            REAL_DOCKERFILE_NAME=$(basename $REAL_DOCKERFILE)
            echo "PYTHON_DOCKERFILE=${REAL_DOCKERFILE_NAME}" >> $GITHUB_ENV
          else
            echo "PYTHON_DOCKERFILE=${{ env.PYTHON_DOCKERFILE }}" >> $GITHUB_ENV
          fi

      - name: Linting Dockerfile and annotate code inline in the github PR viewer
        id: hadolint
        uses: jbergstroem/hadolint-gh-action@v1.12.2
        with:
          dockerfile: ${{ env.CONTEXT }}/${{ env.BRANCH }}/dev/${{ env.DOCKERFILE }}
          version: ${{ env.HADOLINT_VERSION }}
          annotate: true
          error_level: -1

      - name: Linting Python Dockerfile and annotate code inline in the github PR viewer
        id: python_hadolint
        uses: jbergstroem/hadolint-gh-action@v1.12.2
        with:
          dockerfile: ${{ env.CONTEXT }}/${{ env.BRANCH }}/dev/${{ env.PYTHON_DOCKERFILE }}
          version: ${{ env.HADOLINT_VERSION }}
          annotate: true
          error_level: -1

  build_and_push_test:
    name: runner/test-ckan-spatial-test-pr:${{ github.head_ref }}.*
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # Test only use base Dockerfile
      - name: Linting Dockerfile and annotate code inline in the github PR viewer
        id: hadolint
        uses: jbergstroem/hadolint-gh-action@v1.12.2
        with:
          dockerfile: ${{ env.CONTEXT }}/${{ env.BRANCH }}/test/${{ env.DOCKERFILE }}
          version: ${{ env.HADOLINT_VERSION }}
          annotate: true
          error_level: -1